# This file is a template for a GitHub Actions workflow.
# For more information, see: https://docs.github.com/actions/learn-github-actions/introduction-to-github-actions

name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Package Binary
        run: |
          mkdir dist
          cp target/x86_64-unknown-linux-gnu/release/powe_rs dist/powe_rs-x86_64-unknown-linux-gnu
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: powe_rs-x86_64-unknown-linux-gnu
          path: dist/*

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
