# This file is a template for a GitHub Actions workflow.
# For more information, see: https://docs.github.com/actions/learn-github-actions/introduction-to-github-actions

name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "**"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Add x86_64 target
        run: rustup target add x86_64-unknown-linux-gnu
      - name: Cache cross binary
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cross
          key: ${{ runner.os }}-cross-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cross
        run: |
          if ! command -v cross &> /dev/null; then
            cargo install cross --locked
          fi
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.docker-cross
          key: ${{ runner.os }}-docker-cross-${{ hashFiles('**/Cargo.lock') }}
      - name: Build x86_64
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Build aarch64 (with cross)
        env:
          CROSS_HOME: /tmp/.docker-cross
        run: cross build --release --target aarch64-unknown-linux-gnu
      - name: Package Binaries
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-gnu/release/powe_rs dist/powe_rs-x86_64-unknown-linux-gnu
          cp target/aarch64-unknown-linux-gnu/release/powe_rs dist/powe_rs-aarch64-unknown-linux-gnu
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: powe_rs-binaries
          path: dist/*

  # publish:
  #   name: Publish to crates.io
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Publish
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #       run: cargo publish --locked

  # github-release:
  #   name: GitHub Release
  #   runs-on: ubuntu-latest
  #   needs: publish
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: ./dist
  #     - name: Create Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: ./dist/**/*
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
